name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      javaVersion:
        type: string
        default: '21'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Set Up Java'
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.javaVersion || '21' }}
          distribution: 'temurin'
          cache: 'maven'
      - name: 'Build Project'
        if: runner.os == 'Linux'
        run: mvn --batch-mode --errors --fail-at-end test
        env:
          MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN"
      - name: 'Build Project (skip tests)'
        if: runner.os != 'Linux'
        run: mvn --batch-mode --errors --fail-at-end test -DskipTests
        env:
          MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN"
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
      fail-fast: false
